name: Gource Action
on:
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@v1

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v4
        with:
          name: Gource
          path: ./gource/gource.mp4
